graph TD
    subgraph Subgerente_Karla
        A(( )) --> B[Verificar Abonos en la Cuenta de Dólares]
        B --> C[Notificar Recepción de Pagos al Contador]
    end

    subgraph Contador_Externo
        C --> D[Realizar Asiento Contable según Tipo de Cambio]
        D --> E[Generar Reporte de Flujo de Caja para Impuestos]
        E --> F(( ))
    end

    style A fill:#f9f,stroke:#333,stroke-width:2px
    style F fill:#f9f,stroke:#333,stroke-width:4px