graph LR
    %% Entorno Actual - Manual
    subgraph Macroproceso_Operativo_AS_IS [P01. GESTIÓN DE OPERACIONES LOGÍSTICAS - ACTUAL]
        direction LR
        P1[1. Planificación y Recepción]
        P2[2. Gestión de Almacenamiento]
        P3[3. Despacho de Mercadería]

        P1 -->|Registro manual en Garita y Excel| P2
        P2 -->|Ubicación por memoria / Excel desactualizado| P3
    end

    %% Puntos de Dolor resaltados
    P1 -.-> D1{{"¡Error de Digitación!"}}
    P2 -.-> D2{{"¡Falta de Ubicabilidad!"}}
    P3 -.-> D3{{"¡Pedido no cerrado / Faltantes!"}}

    Entrada([Llegada de Mercadería / Guías Físicas]) --> P1
    P3 --> Salida([Salida con Riesgo de Reclamos])

    %% Estilo
    style Macroproceso_Operativo_AS_IS fill:#ffebee,stroke:#c62828,stroke-width:2px
    style D1 fill:#fff,stroke:#c62828,color:#c62828
    style D2 fill:#fff,stroke:#c62828,color:#c62828
    style D3 fill:#fff,stroke:#c62828,color:#c62828